// AUTO-GENERATED by scripts/build_goalbank_from_text.mjs
// Do not hand-edit. Edit the source text file instead.

import type { GoalTemplate } from "@/lib/goalBank";

export const READING_COMPREHENSION_GOAL_BANK: GoalTemplate[] = [
];
