// AUTO-GENERATED by scripts/build_goalbank_from_text.mjs
// Do not hand-edit. Edit the source text file instead.

import type { GoalTemplate } from "@/lib/goalBank";

export const FUNCTIONAL_READING_GOAL_BANK: GoalTemplate[] = [];
