// scripts/build_goalbank_from_text.mjs
// Usage:
//   node scripts/build_goalbank_from_text.mjs resources/goalbanks/transition.txt src/lib/goalBank.transition.ts TRANSITION_GOAL_BANK Transition
//   node scripts/build_goalbank_from_text.mjs resources/goalbanks/functional-reading.txt src/lib/goalBank.functionalReading.ts FUNCTIONAL_READING_GOAL_BANK Reading

import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";

function hashId(s) {
  return crypto.createHash("sha1").update(s).digest("hex").slice(0, 10);
}

function normPlaceholders(s) {
  return s
    .replace(/\[Student Name\]/gi, "[STUDENT]")
    .replace(/\[Student\]/gi, "[STUDENT]");
}

function isHeading(line) {
  const t = line.trim();
  if (!t) return false;
  if (t.startsWith("By the end")) return false;
  if (t.startsWith("*")) return false;
  const promoStarts = [
    "Curious about",
    "Need more",
    "Want more",
    "Boost",
    "Reading comprehension",
    "Social skills matter",
    "Working with",
    "Need help",
    "If planning is",
  ];
  if (promoStarts.some((p) => t.startsWith(p))) return false;
  if (t.length < 6) return false;
  const punct = (t.match(/[.,;:!?]/g) || []).length;
  return punct <= 1 && !t.endsWith(".");
}

function isGoal(line) {
  const t = line.trim();
  if (!t) return false;
  return t.startsWith("By the end of the IEP period");
}

function clean(line) {
  return line.trim().replace(/\s+/g, " ");
}

function tagsFromText(text, category, subcategory) {
  const tags = new Set();
  tags.add(category.toLowerCase());
  if (subcategory) tags.add(subcategory.toLowerCase());

  const t = text.toLowerCase();
  if (t.includes("community")) tags.add("community");
  if (t.includes("vocational")) tags.add("vocational");
  if (t.includes("checklist")) tags.add("checklist");
  if (t.includes("budget")) tags.add("budget");
  if (t.includes("transport")) tags.add("transportation");
  if (t.includes("safety")) tags.add("safety");
  if (t.includes("resume") || t.includes("résumé")) tags.add("resume");
  if (t.includes("job application")) tags.add("job application");
  if (t.includes("money") || t.includes("cash") || t.includes("debit") || t.includes("bank")) {
    tags.add("financial literacy");
  }
  if (t.includes("directions")) tags.add("directions");
  if (t.includes("sign") || t.includes("symbols") || t.includes("environmental print")) {
    tags.add("signs/symbols");
  }

  if (t.includes("% accuracy")) tags.add("accuracy");
  if (t.includes("out of")) tags.add("trials/opportunities");
  if (t.includes("as measured")) tags.add("data collection");

  return Array.from(tags);
}

function buildTs({ items, exportConstName, categoryLabel }) {
  const lines = [];
  lines.push(`// AUTO-GENERATED by scripts/build_goalbank_from_text.mjs`);
  lines.push(`// Do not hand-edit. Edit the source text file instead.\n`);
  lines.push(`import type { GoalTemplate } from "@/lib/goalBank";\n`);
  lines.push(`export const ${exportConstName}: GoalTemplate[] = [`);

  for (const it of items) {
    const txt = it.text.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
    const tags = JSON.stringify(it.tags);
    lines.push(`  {`);
    lines.push(`    id: "${it.id}",`);
    lines.push(`    category: "${categoryLabel}",`);
    if (it.subcategory) lines.push(`    subcategory: "${it.subcategory}",`);
    lines.push(`    text: "${txt}",`);
    lines.push(`    tags: ${tags},`);
    lines.push(`  },`);
  }

  lines.push(`];\n`);
  return lines.join("\n");
}

function main() {
  const [inPath, outPath, exportConstName, categoryLabel] = process.argv.slice(2);
  if (!inPath || !outPath || !exportConstName || !categoryLabel) {
    console.error(
      `Usage: node scripts/build_goalbank_from_text.mjs <input.txt> <output.ts> <EXPORT_NAME> <CategoryLabel>`
    );
    process.exit(1);
  }

  const raw = fs.readFileSync(inPath, "utf8");
  const lines = raw.split(/\r?\n/).map(clean);

  let subcategory = "";
  const items = [];

  for (const line of lines) {
    if (!line) continue;

    if (isHeading(line)) {
      subcategory = line
        .replace(/IEP Goals$/i, "")
        .replace(/Goal(s)?$/i, "")
        .trim();
      continue;
    }

    if (isGoal(line)) {
      const text = normPlaceholders(line);
      const id = `${categoryLabel.toLowerCase()}-${hashId(`${subcategory}::${text}`)}`;
      const tags = tagsFromText(text, categoryLabel, subcategory);
      items.push({ id, subcategory: subcategory || undefined, text, tags });
    }
  }

  const ts = buildTs({ items, exportConstName, categoryLabel });
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, ts, "utf8");

  console.log(`✅ Parsed ${items.length} goals`);
  console.log(`✅ Wrote ${outPath}`);
}

main();
